@baseUrl = http://localhost:3000

### READ ALL OWNERS
GET {{baseUrl}}/owners

### READ OWNER BY ID (and his pets)
GET {{baseUrl}}/owners/2

### CREATE OWNER
POST {{baseUrl}}/owners
Content-Type: application/json

{
    "name": "haj",
    "age": 21,
    "phone_number": "123-456-7890",
    "address": "12 St"
}

### DELETE OWNER (and his pets)
DELETE {{baseUrl}}/owners/16

### UPDATE OWNER
PUT {{baseUrl}}/owners/2
Content-Type: application/json

{
    "name": "hadje",
    "age": 24
}