@baseUrl = http://localhost:3000

### READ ALL OWNERS
GET {{baseUrl}}/owners

### READ OWNER BY ID
GET {{baseUrl}}/owners/9

### CREATE OWNER
POST {{baseUrl}}/owners
Content-Type: application/json

{
    "name": "Lea Michele",
    "age": 30,
    "phone_number": "123-456-7890",
    "address": "1234 Elm St"
}

### DELETE OWNER
DELETE {{baseUrl}}/owners/9

### UPDATE OWNER
PUT {{baseUrl}}/owners/1
Content-Type: application/json

{
    "name": "bob",
    "age": 30
}