@baseUrl = http://localhost:3000

### READ ALL PETS
GET {{baseUrl}}/pets

### READ ONE PET (with his owner's info)
GET {{baseUrl}}/pets/2

### CREATE A PET
POST {{baseUrl}}/pets
Content-Type: application/json

{
  "name": "yuumi",
  "species": "cat",
  "age": 3,
  "owner_id": 1
}

### CREATE A PET (with invalid owner_id)
POST {{baseUrl}}/pets
Content-Type: application/json

{
  "name": "bobi",
  "species": "dog",
  "age": 3,
  "owner_id": 9
}

### DELETE A PET
DELETE {{baseUrl}}/pets/5

### UPDATE A PET
PUT {{baseUrl}}/pets/4
Content-Type: application/json

{
  "name": "bobi",
  "species": "dog",
  "owner_id": 1
}