@baseUrl = http://localhost:3000

### READ ALL PETS
GET {{baseUrl}}/pets

### READ ONE PET (with his owner's info)
GET {{baseUrl}}/pets/3

### INSERT A PET (associate it with an owner)
POST {{baseUrl}}/pets
Content-Type: application/json

{
  "name": "yuumi",
  "species": "kitten",
  "age": 3,
  "owner_id": 15
}

### DELETE A PET
DELETE {{baseUrl}}/pets/2

### UPDATE A PET
PUT {{baseUrl}}/pets/3
Content-Type: application/json

{
  "name": "yuumi",
  "species": "kitty",
  "owner_id": 14
}