@baseUrl = http://localhost:3000

### READ ALL PETS
GET {{baseUrl}}/pets

### READ ONE PET
GET {{baseUrl}}/pets/1

### CREATE PET
POST {{baseUrl}}/pets
Content-Type: application/json

{
  "name": "yuumi",
  "species": "cat",
  "age": 3,
  "owner_id": 1
}

### CREATE PET (with invalid owner_id)
POST {{baseUrl}}/pets
Content-Type: application/json

{
  "name": "bobi",
  "species": "dog",
  "age": 3,
  "owner_id": 9
}

### DELETE PET
DELETE {{baseUrl}}/pets/8